/** Common Hindu gotras as listed on Indian matrimonial houses. Alphabetical. */
export const GOTRAS = [
  "Aatharvas",
  "Agasthi",
  "Agastya",
  "Agni",
  "Agnihotri",
  "Ahabhunasa",
  "Airan",
  "Alambayana",
  "Alampayana",
  "Angiras",
  "Angirasa",
  "Arrishinimi",
  "Athreyasya / Athreyasa",
  "Atreya",
  "Atri",
  "Attarishi",
  "Aukshanas",
  "Aushanas",
  "Awasthi",
  "Babhravya",
  "Badarayana",
  "Baijvayas",
  "Bansal",
  "Bashan",
  "Bhandal",
  "Bharadwaj",
  "Bhargava / Bhargav",
  "Bhasyan",
  "Bhrigu",
  "Bindal",
  "Chandratre",
  "Daksha",
  "Dalabhya",
  "Dhananjaya",
  "Dhoumya",
  "Garga",
  "Gargya",
  "Gautam",
  "Gautama",
  "Goyal",
  "Harita",
  "Haritas",
  "Jamadagni",
  "Jatukarna",
  "Jindal",
  "Kadam",
  "Kansal",
  "Kanva",
  "Kapila",
  "Kapilendra",
  "Kashyapa",
  "Kaundinya",
  "Kaushik",
  "Kaushika",
  "Kautilya",
  "Kautsa",
  "Koshish",
  "Krishnatreya",
  "Kutsa",
  "Lakhi",
  "Lohit",
  "Mandavya",
  "Markandeya",
  "Mauna Bhargava",
  "Maudgalya",
  "Mittal",
  "Mudgal",
  "Nagesh",
  "Nanda",
  "Parashara",
  "Paithinasa",
  "Pulaha",
  "Pulastya",
  "Rathitara",
  "Sandilya",
  "Sankhyayana",
  "Sankriti",
  "Savarna",
  "Shandilya",
  "Shandilyasa",
  "Shunaka",
  "Singhal",
  "Srivatsa",
  "Suryadhwaja",
  "Tayal",
  "Upamanyu",
  "Upreti",
  "Vadhula",
  "Vashishta",
  "Vatsa",
  "Vishnuvardhana",
  "Vishwamitra",
  "Vyaghrapada",
  "Vyasa",
] as const;

export const GOTRA_DONT_KNOW = "Don't know";
export const GOTRA_OTHER = "Other";

/** Own gothra and hoped-for gothra: Don't know and Other first, then A–Z. */
export const GOTRA_CHOICES = [GOTRA_DONT_KNOW, GOTRA_OTHER, ...GOTRAS] as const;
