export type ProfileFormValues = {
  id?: string;
  creator_relationship?: string;
  profile_type?: string;
  subject_full_name?: string;
  surname?: string | null;
  date_of_birth?: string;
  birth_time?: string | null;
  mother_tongue?: string | null;
  height_cm?: number | null;
  marital_status?: string | null;
  diet?: string | null;
  native_country?: string | null;
  native_state?: string | null;
  native_city?: string | null;
  current_city?: string | null;
  current_state?: string | null;
  qualification?: string | null;
  occupation?: string | null;
  employed_in?: string | null;
  income_band?: string | null;
  employer_name?: string | null;
  settle_abroad?: string | null;
  future_ambition?: string | null;
  family_type?: string | null;
  birth_city?: string | null;
  college_name?: string | null;
  hobbies?: string | null;
  brothers_count?: number | null;
  brothers_married_count?: number | null;
  sisters_count?: number | null;
  sisters_married_count?: number | null;
  father_name?: string | null;
  father_occupation?: string | null;
  mother_name?: string | null;
  mother_occupation?: string | null;
  siblings_note?: string | null;
  family_status?: string | null;
  family_location?: string | null;
  physical_status?: string | null;
  health_notes?: string | null;
  sub_community?: string | null;
  blood_group?: string | null;
  grew_up_in?: string | null;
  living_arrangement?: string | null;
  gotra?: string | null;
  rashi?: string | null;
  lagna?: string | null;
  nakshatra?: string | null;
  nakshatra_pada?: string | null;
  gana?: string | null;
  yoni_animal?: string | null;
  manglik?: string | null;
  citizenship?: string | null;
  pin_code?: string | null;
  current_country?: string | null;
  hobby_list?: string[] | null;
  pref_age_min?: number | null;
  pref_age_max?: number | null;
  pref_marital?: string | string[] | null;
  pref_maritals?: string[] | null;
  pref_education?: string | string[] | null;
  pref_educations?: string[] | null;
  pref_occupation?: string | string[] | null;
  pref_occupations?: string[] | null;
  pref_country?: string | string[] | null;
  pref_countries?: string[] | null;
  pref_notes?: string | null;
  known_languages?: string[] | null;
  pref_tongues?: string[] | null;
  pref_religions?: string[] | null;
  pref_communities?: string[] | null;
  pref_state?: string | string[] | null;
  pref_states?: string[] | null;
  pref_cities?: string[] | null;
  pref_height_min?: number | null;
  pref_height_max?: number | null;
  pref_diets?: string[] | null;
  pref_incomes?: string[] | null;
  pref_employed?: string[] | null;
  pref_managed?: string[] | null;
  pref_gothra?: string[] | null;
  pref_horoscope?: string | null;
  about?: string | null;
  religion_id?: string | null;
  community_id?: string | null;
  prefer_not_community?: boolean;
  subject_mobile?: string | null;
  phone_otp_verified_at?: string | null;
  member_code?: string | null;
};
