-- Remaining registration catalogs. Run after 001–024.

begin;

create table if not exists public.lookup_options (
  id uuid primary key default gen_random_uuid(),
  kind text not null,
  name text not null,
  code text,
  hint text,
  sort_order int not null default 0,
  unique (kind, name)
);

insert into public.lookup_options (kind, name, code, hint, sort_order) values
  ('employed_in', 'Student', null, null, 0),
  ('employed_in', 'Private company', null, null, 1),
  ('employed_in', 'Government', null, null, 2),
  ('employed_in', 'Defence', null, null, 3),
  ('employed_in', 'Public sector', null, null, 4),
  ('employed_in', 'Business / self-employed', null, null, 5),
  ('employed_in', 'Not working', null, null, 6),
  ('family_type', 'Nuclear', null, null, 0),
  ('family_type', 'Joint', null, null, 1),
  ('family_type', 'Other', null, null, 2),
  ('family_status', 'Lower middle class', null, null, 0),
  ('family_status', 'Middle class', null, null, 1),
  ('family_status', 'Upper middle class', null, null, 2),
  ('family_status', 'Upper class', null, null, 3),
  ('family_status', 'Prefer not to say', null, null, 4),
  ('physical_status', 'No disability', null, null, 0),
  ('physical_status', 'Has a disability', null, null, 1),
  ('physical_status', 'Prefer not to say', null, null, 2),
  ('blood_group', 'A+', null, null, 0),
  ('blood_group', 'A-', null, null, 1),
  ('blood_group', 'B+', null, null, 2),
  ('blood_group', 'B-', null, null, 3),
  ('blood_group', 'AB+', null, null, 4),
  ('blood_group', 'AB-', null, null, 5),
  ('blood_group', 'O+', null, null, 6),
  ('blood_group', 'O-', null, null, 7),
  ('blood_group', 'Don''t know', null, null, 8),
  ('hobby', 'Art', null, null, 0),
  ('hobby', 'Cooking', null, null, 1),
  ('hobby', 'Dance', null, null, 2),
  ('hobby', 'Movies', null, null, 3),
  ('hobby', 'Music', null, null, 4),
  ('hobby', 'Photography', null, null, 5),
  ('hobby', 'Reading', null, null, 6),
  ('hobby', 'Shopping', null, null, 7),
  ('hobby', 'Singing', null, null, 8),
  ('hobby', 'Social media', null, null, 9),
  ('hobby', 'Sport', null, null, 10),
  ('hobby', 'Travel', null, null, 11),
  ('hobby', 'Writing', null, null, 12),
  ('hobby', 'Yoga', null, null, 13),
  ('country', 'India', null, null, 0),
  ('country', 'Afghanistan', null, null, 1),
  ('country', 'Albania', null, null, 2),
  ('country', 'Algeria', null, null, 3),
  ('country', 'Argentina', null, null, 4),
  ('country', 'Armenia', null, null, 5),
  ('country', 'Australia', null, null, 6),
  ('country', 'Austria', null, null, 7),
  ('country', 'Azerbaijan', null, null, 8),
  ('country', 'Bahrain', null, null, 9),
  ('country', 'Bangladesh', null, null, 10),
  ('country', 'Belarus', null, null, 11),
  ('country', 'Belgium', null, null, 12),
  ('country', 'Bhutan', null, null, 13),
  ('country', 'Bolivia', null, null, 14),
  ('country', 'Bosnia and Herzegovina', null, null, 15),
  ('country', 'Botswana', null, null, 16),
  ('country', 'Brazil', null, null, 17),
  ('country', 'Brunei', null, null, 18),
  ('country', 'Bulgaria', null, null, 19),
  ('country', 'Cambodia', null, null, 20),
  ('country', 'Cameroon', null, null, 21),
  ('country', 'Canada', null, null, 22),
  ('country', 'Chile', null, null, 23),
  ('country', 'China', null, null, 24),
  ('country', 'Colombia', null, null, 25),
  ('country', 'Costa Rica', null, null, 26),
  ('country', 'Croatia', null, null, 27),
  ('country', 'Cyprus', null, null, 28),
  ('country', 'Czechia', null, null, 29),
  ('country', 'Denmark', null, null, 30),
  ('country', 'Egypt', null, null, 31),
  ('country', 'Estonia', null, null, 32),
  ('country', 'Ethiopia', null, null, 33),
  ('country', 'Fiji', null, null, 34),
  ('country', 'Finland', null, null, 35),
  ('country', 'France', null, null, 36),
  ('country', 'Georgia', null, null, 37),
  ('country', 'Germany', null, null, 38),
  ('country', 'Ghana', null, null, 39),
  ('country', 'Greece', null, null, 40),
  ('country', 'Hong Kong', null, null, 41),
  ('country', 'Hungary', null, null, 42),
  ('country', 'Iceland', null, null, 43),
  ('country', 'Indonesia', null, null, 44),
  ('country', 'Iran', null, null, 45),
  ('country', 'Iraq', null, null, 46),
  ('country', 'Ireland', null, null, 47),
  ('country', 'Israel', null, null, 48),
  ('country', 'Italy', null, null, 49),
  ('country', 'Jamaica', null, null, 50),
  ('country', 'Japan', null, null, 51),
  ('country', 'Jordan', null, null, 52),
  ('country', 'Kazakhstan', null, null, 53),
  ('country', 'Kenya', null, null, 54),
  ('country', 'Kuwait', null, null, 55),
  ('country', 'Kyrgyzstan', null, null, 56),
  ('country', 'Laos', null, null, 57),
  ('country', 'Latvia', null, null, 58),
  ('country', 'Lebanon', null, null, 59),
  ('country', 'Lithuania', null, null, 60),
  ('country', 'Luxembourg', null, null, 61),
  ('country', 'Malaysia', null, null, 62),
  ('country', 'Maldives', null, null, 63),
  ('country', 'Malta', null, null, 64),
  ('country', 'Mauritius', null, null, 65),
  ('country', 'Mexico', null, null, 66),
  ('country', 'Moldova', null, null, 67),
  ('country', 'Mongolia', null, null, 68),
  ('country', 'Morocco', null, null, 69),
  ('country', 'Myanmar', null, null, 70),
  ('country', 'Nepal', null, null, 71),
  ('country', 'Netherlands', null, null, 72),
  ('country', 'New Zealand', null, null, 73),
  ('country', 'Nigeria', null, null, 74),
  ('country', 'North Macedonia', null, null, 75),
  ('country', 'Norway', null, null, 76),
  ('country', 'Oman', null, null, 77),
  ('country', 'Pakistan', null, null, 78),
  ('country', 'Palestine', null, null, 79),
  ('country', 'Panama', null, null, 80),
  ('country', 'Peru', null, null, 81),
  ('country', 'Philippines', null, null, 82),
  ('country', 'Poland', null, null, 83),
  ('country', 'Portugal', null, null, 84),
  ('country', 'Qatar', null, null, 85),
  ('country', 'Romania', null, null, 86),
  ('country', 'Russia', null, null, 87),
  ('country', 'Rwanda', null, null, 88),
  ('country', 'Saudi Arabia', null, null, 89),
  ('country', 'Serbia', null, null, 90),
  ('country', 'Singapore', null, null, 91),
  ('country', 'Slovakia', null, null, 92),
  ('country', 'Slovenia', null, null, 93),
  ('country', 'South Africa', null, null, 94),
  ('country', 'South Korea', null, null, 95),
  ('country', 'Spain', null, null, 96),
  ('country', 'Sri Lanka', null, null, 97),
  ('country', 'Sweden', null, null, 98),
  ('country', 'Switzerland', null, null, 99),
  ('country', 'Taiwan', null, null, 100),
  ('country', 'Tajikistan', null, null, 101),
  ('country', 'Tanzania', null, null, 102),
  ('country', 'Thailand', null, null, 103),
  ('country', 'Trinidad and Tobago', null, null, 104),
  ('country', 'Tunisia', null, null, 105),
  ('country', 'Turkey', null, null, 106),
  ('country', 'Turkmenistan', null, null, 107),
  ('country', 'Uganda', null, null, 108),
  ('country', 'Ukraine', null, null, 109),
  ('country', 'United Arab Emirates', null, null, 110),
  ('country', 'United Kingdom', null, null, 111),
  ('country', 'United States', null, null, 112),
  ('country', 'Uruguay', null, null, 113),
  ('country', 'Uzbekistan', null, null, 114),
  ('country', 'Vietnam', null, null, 115),
  ('country', 'Yemen', null, null, 116),
  ('country', 'Zambia', null, null, 117),
  ('country', 'Zimbabwe', null, null, 118),
  ('country', 'Other', null, null, 119),
  ('hope_country', 'Any country', null, null, 0),
  ('hope_country', 'India', null, null, 1),
  ('hope_country', 'United Arab Emirates', null, null, 2),
  ('hope_country', 'Singapore', null, null, 3),
  ('hope_country', 'United States', null, null, 4),
  ('hope_country', 'United Kingdom', null, null, 5),
  ('hope_country', 'Canada', null, null, 6),
  ('hope_country', 'Australia', null, null, 7),
  ('hope_country', 'Other', null, null, 8),
  ('residency', 'Citizen', null, null, 0),
  ('residency', 'Permanent resident', null, null, 1),
  ('residency', 'Work visa', null, null, 2),
  ('residency', 'Student visa', null, null, 3),
  ('residency', 'Overseas citizen', null, null, 4),
  ('residency', 'Other', null, null, 5),
  ('income', 'Prefer not to say', null, null, 0),
  ('income', 'Student / not earning', null, null, 1),
  ('income', 'Up to ₹5 lakh', null, null, 2),
  ('income', '₹5–10 lakh', null, null, 3),
  ('income', '₹10–15 lakh', null, null, 4),
  ('income', '₹15–20 lakh', null, null, 5),
  ('income', '₹20–25 lakh', null, null, 6),
  ('income', '₹25–30 lakh', null, null, 7),
  ('income', '₹30–35 lakh', null, null, 8),
  ('income', '₹35–40 lakh', null, null, 9),
  ('income', '₹40–45 lakh', null, null, 10),
  ('income', '₹45–50 lakh', null, null, 11),
  ('income', '₹50–55 lakh', null, null, 12),
  ('income', '₹55–60 lakh', null, null, 13),
  ('income', '₹60–65 lakh', null, null, 14),
  ('income', '₹65–70 lakh', null, null, 15),
  ('income', '₹70–75 lakh', null, null, 16),
  ('income', '₹75–80 lakh', null, null, 17),
  ('income', '₹80–85 lakh', null, null, 18),
  ('income', '₹85–90 lakh', null, null, 19),
  ('income', '₹90–95 lakh', null, null, 20),
  ('income', '₹95 lakh–₹1 crore', null, null, 21),
  ('income', 'Above ₹1 crore', null, null, 22),
  ('hope_income', 'Greater than ₹5 lakh', null, null, 0),
  ('hope_income', 'Greater than ₹10 lakh', null, null, 1),
  ('hope_income', 'Greater than ₹15 lakh', null, null, 2),
  ('hope_income', 'Greater than ₹20 lakh', null, null, 3),
  ('hope_income', 'Greater than ₹25 lakh', null, null, 4),
  ('hope_income', 'Greater than ₹30 lakh', null, null, 5),
  ('hope_income', 'Greater than ₹35 lakh', null, null, 6),
  ('hope_income', 'Greater than ₹40 lakh', null, null, 7),
  ('hope_income', 'Greater than ₹45 lakh', null, null, 8),
  ('hope_income', 'Greater than ₹50 lakh', null, null, 9),
  ('hope_income', 'Greater than ₹60 lakh', null, null, 10),
  ('hope_income', 'Greater than ₹75 lakh', null, null, 11),
  ('hope_income', 'Greater than ₹1 crore', null, null, 12),
  ('pref_managed', 'Self', null, null, 0),
  ('pref_managed', 'Family', null, null, 1),
  ('horoscope', 'Yes', null, null, 0),
  ('horoscope', 'No', null, null, 1),
  ('horoscope', 'Does not matter', null, null, 2),
  ('gotra', 'Don''t know', null, null, 0),
  ('gotra', 'Other', null, null, 1),
  ('gotra', 'Aatharvas', null, null, 2),
  ('gotra', 'Agasthi', null, null, 3),
  ('gotra', 'Agastya', null, null, 4),
  ('gotra', 'Agni', null, null, 5),
  ('gotra', 'Agnihotri', null, null, 6),
  ('gotra', 'Ahabhunasa', null, null, 7),
  ('gotra', 'Airan', null, null, 8),
  ('gotra', 'Alambayana', null, null, 9),
  ('gotra', 'Alampayana', null, null, 10),
  ('gotra', 'Angiras', null, null, 11),
  ('gotra', 'Angirasa', null, null, 12),
  ('gotra', 'Arrishinimi', null, null, 13),
  ('gotra', 'Athreyasya / Athreyasa', null, null, 14),
  ('gotra', 'Atreya', null, null, 15),
  ('gotra', 'Atri', null, null, 16),
  ('gotra', 'Attarishi', null, null, 17),
  ('gotra', 'Aukshanas', null, null, 18),
  ('gotra', 'Aushanas', null, null, 19),
  ('gotra', 'Awasthi', null, null, 20),
  ('gotra', 'Babhravya', null, null, 21),
  ('gotra', 'Badarayana', null, null, 22),
  ('gotra', 'Baijvayas', null, null, 23),
  ('gotra', 'Bansal', null, null, 24),
  ('gotra', 'Bashan', null, null, 25),
  ('gotra', 'Bhandal', null, null, 26),
  ('gotra', 'Bharadwaj', null, null, 27),
  ('gotra', 'Bhargava / Bhargav', null, null, 28),
  ('gotra', 'Bhasyan', null, null, 29),
  ('gotra', 'Bhrigu', null, null, 30),
  ('gotra', 'Bindal', null, null, 31),
  ('gotra', 'Chandratre', null, null, 32),
  ('gotra', 'Daksha', null, null, 33),
  ('gotra', 'Dalabhya', null, null, 34),
  ('gotra', 'Dhananjaya', null, null, 35),
  ('gotra', 'Dhoumya', null, null, 36),
  ('gotra', 'Garga', null, null, 37),
  ('gotra', 'Gargya', null, null, 38),
  ('gotra', 'Gautam', null, null, 39),
  ('gotra', 'Gautama', null, null, 40),
  ('gotra', 'Goyal', null, null, 41),
  ('gotra', 'Harita', null, null, 42),
  ('gotra', 'Haritas', null, null, 43),
  ('gotra', 'Jamadagni', null, null, 44),
  ('gotra', 'Jatukarna', null, null, 45),
  ('gotra', 'Jindal', null, null, 46),
  ('gotra', 'Kadam', null, null, 47),
  ('gotra', 'Kansal', null, null, 48),
  ('gotra', 'Kanva', null, null, 49),
  ('gotra', 'Kapila', null, null, 50),
  ('gotra', 'Kapilendra', null, null, 51),
  ('gotra', 'Kashyapa', null, null, 52),
  ('gotra', 'Kaundinya', null, null, 53),
  ('gotra', 'Kaushik', null, null, 54),
  ('gotra', 'Kaushika', null, null, 55),
  ('gotra', 'Kautilya', null, null, 56),
  ('gotra', 'Kautsa', null, null, 57),
  ('gotra', 'Koshish', null, null, 58),
  ('gotra', 'Krishnatreya', null, null, 59),
  ('gotra', 'Kutsa', null, null, 60),
  ('gotra', 'Lakhi', null, null, 61),
  ('gotra', 'Lohit', null, null, 62),
  ('gotra', 'Mandavya', null, null, 63),
  ('gotra', 'Markandeya', null, null, 64),
  ('gotra', 'Mauna Bhargava', null, null, 65),
  ('gotra', 'Maudgalya', null, null, 66),
  ('gotra', 'Mittal', null, null, 67),
  ('gotra', 'Mudgal', null, null, 68),
  ('gotra', 'Nagesh', null, null, 69),
  ('gotra', 'Nanda', null, null, 70),
  ('gotra', 'Parashara', null, null, 71),
  ('gotra', 'Paithinasa', null, null, 72),
  ('gotra', 'Pulaha', null, null, 73),
  ('gotra', 'Pulastya', null, null, 74),
  ('gotra', 'Rathitara', null, null, 75),
  ('gotra', 'Sandilya', null, null, 76),
  ('gotra', 'Sankhyayana', null, null, 77),
  ('gotra', 'Sankriti', null, null, 78),
  ('gotra', 'Savarna', null, null, 79),
  ('gotra', 'Shandilya', null, null, 80),
  ('gotra', 'Shandilyasa', null, null, 81),
  ('gotra', 'Shunaka', null, null, 82),
  ('gotra', 'Singhal', null, null, 83),
  ('gotra', 'Srivatsa', null, null, 84),
  ('gotra', 'Suryadhwaja', null, null, 85),
  ('gotra', 'Tayal', null, null, 86),
  ('gotra', 'Upamanyu', null, null, 87),
  ('gotra', 'Upreti', null, null, 88),
  ('gotra', 'Vadhula', null, null, 89),
  ('gotra', 'Vashishta', null, null, 90),
  ('gotra', 'Vatsa', null, null, 91),
  ('gotra', 'Vishnuvardhana', null, null, 92),
  ('gotra', 'Vishwamitra', null, null, 93),
  ('gotra', 'Vyaghrapada', null, null, 94),
  ('gotra', 'Vyasa', null, null, 95),
  ('creator_role', 'Self', 'self', 'I am the bride or groom', 0),
  ('creator_role', 'Parent', 'parent', 'Mother or father', 1),
  ('creator_role', 'Sister', 'sister', 'Posting for family', 2),
  ('creator_role', 'Brother', 'brother', 'Posting for family', 3),
  ('creator_role', 'Sister or brother', 'sibling', 'Posting for family', 4),
  ('creator_role', 'Guardian', 'guardian', 'Caretaker of the person', 5),
  ('creator_role', 'Relative', 'relative', 'Kept for older profiles', 6),
  ('creator_role', 'Friend', 'friend', 'Kept for older profiles', 7),
  ('creator_role', 'Colleague', 'colleague', 'Kept for older profiles', 8)
on conflict (kind, name) do nothing;

alter table public.lookup_options enable row level security;
drop policy if exists lookup_options_read on public.lookup_options;
create policy lookup_options_read on public.lookup_options for select using (true);
grant select on public.lookup_options to anon, authenticated;

commit;
