-- Shaadi.com-style religion and community catalog.
-- Run after 001–002. Existing rows are kept (on conflict do nothing).

begin;

insert into public.religions (slug, name, sort_order) values
  ('hindu', 'Hindu', 1),
  ('muslim', 'Muslim', 2),
  ('christian', 'Christian', 3),
  ('sikh', 'Sikh', 4),
  ('jain', 'Jain', 5),
  ('buddhist', 'Buddhist', 6),
  ('parsi', 'Parsi', 7),
  ('jewish', 'Jewish', 8),
  ('spiritual', 'Spiritual - not religious', 9),
  ('other', 'Other', 10)
on conflict (slug) do update
  set name = excluded.name,
      sort_order = excluded.sort_order;

insert into public.communities (religion_id, slug, name)
select r.id, v.slug, v.name
from public.religions r
join (values
  ('hindu', '96k-kokanastha', '96K Kokanastha'),
  ('hindu', 'adi-andhra', 'Adi Andhra'),
  ('hindu', 'adi-dravida', 'Adi Dravida'),
  ('hindu', 'adi-karnataka', 'Adi Karnataka'),
  ('hindu', 'agamudayar', 'Agamudayar'),
  ('hindu', 'agarwal', 'Agarwal'),
  ('hindu', 'agnikula-kshatriya', 'Agnikula Kshatriya'),
  ('hindu', 'agri', 'Agri'),
  ('hindu', 'ahir', 'Ahir'),
  ('hindu', 'ahom', 'Ahom'),
  ('hindu', 'ambalavasi', 'Ambalavasi'),
  ('hindu', 'arekatica', 'Arekatica'),
  ('hindu', 'arora', 'Arora'),
  ('hindu', 'arunthathiyar', 'Arunthathiyar'),
  ('hindu', 'arya-vysya', 'Arya Vysya'),
  ('hindu', 'ayyaraka', 'Ayyaraka'),
  ('hindu', 'badaga', 'Badaga'),
  ('hindu', 'baghel-pal-gaderiya', 'Baghel / Pal / Gaderiya'),
  ('hindu', 'bahi', 'Bahi'),
  ('hindu', 'baidya', 'Baidya'),
  ('hindu', 'baishnab', 'Baishnab'),
  ('hindu', 'baishya', 'Baishya'),
  ('hindu', 'bajantri', 'Bajantri'),
  ('hindu', 'balija', 'Balija'),
  ('hindu', 'banayat-oriya', 'Banayat Oriya'),
  ('hindu', 'banik', 'Banik'),
  ('hindu', 'baniya', 'Baniya'),
  ('hindu', 'baniya-bania', 'Baniya - Bania'),
  ('hindu', 'baniya-kumuti', 'Baniya - Kumuti'),
  ('hindu', 'banjara', 'Banjara'),
  ('hindu', 'barai', 'Barai'),
  ('hindu', 'bari', 'Bari'),
  ('hindu', 'baria', 'Baria'),
  ('hindu', 'barujibi', 'Barujibi'),
  ('hindu', 'bhandari', 'Bhandari'),
  ('hindu', 'bhatia', 'Bhatia'),
  ('hindu', 'bhatraju', 'Bhatraju'),
  ('hindu', 'bhavasar-kshatriya', 'Bhavasar Kshatriya'),
  ('hindu', 'bhil', 'Bhil'),
  ('hindu', 'bhoi', 'Bhoi'),
  ('hindu', 'bhovi', 'Bhovi'),
  ('hindu', 'bhoyar', 'Bhoyar'),
  ('hindu', 'billava', 'Billava'),
  ('hindu', 'bista', 'Bista'),
  ('hindu', 'boyer', 'Boyer'),
  ('hindu', 'brahmbatt', 'Brahmbatt'),
  ('hindu', 'brahmin', 'Brahmin'),
  ('hindu', 'brahmin-6000-niyogi', 'Brahmin - 6000 Niyogi'),
  ('hindu', 'brahmin-anavil', 'Brahmin - Anavil'),
  ('hindu', 'brahmin-audichya', 'Brahmin - Audichya'),
  ('hindu', 'brahmin-bardai', 'Brahmin - Bardai'),
  ('hindu', 'brahmin-barendra', 'Brahmin - Barendra'),
  ('hindu', 'brahmin-bhargav', 'Brahmin - Bhargav'),
  ('hindu', 'brahmin-bhatt', 'Brahmin - Bhatt'),
  ('hindu', 'brahmin-bhumihar', 'Brahmin - Bhumihar'),
  ('hindu', 'brahmin-daivadnya', 'Brahmin - Daivadnya'),
  ('hindu', 'brahmin-danua', 'Brahmin - Danua'),
  ('hindu', 'brahmin-deshastha', 'Brahmin - Deshastha'),
  ('hindu', 'brahmin-dhiman', 'Brahmin - Dhiman'),
  ('hindu', 'brahmin-dravida', 'Brahmin - Dravida'),
  ('hindu', 'brahmin-garhwali', 'Brahmin - Garhwali'),
  ('hindu', 'brahmin-gaud-saraswat', 'Brahmin - Gaud Saraswat'),
  ('hindu', 'brahmin-gaur', 'Brahmin - Gaur'),
  ('hindu', 'brahmin-goswami', 'Brahmin - Goswami'),
  ('hindu', 'brahmin-gujar-gaur', 'Brahmin - Gujar Gaur'),
  ('hindu', 'brahmin-gurukkal', 'Brahmin - Gurukkal'),
  ('hindu', 'brahmin-halua', 'Brahmin - Halua'),
  ('hindu', 'brahmin-havyaka', 'Brahmin - Havyaka'),
  ('hindu', 'brahmin-hoysala', 'Brahmin - Hoysala'),
  ('hindu', 'brahmin-iyengar', 'Brahmin - Iyengar'),
  ('hindu', 'brahmin-iyer', 'Brahmin - Iyer'),
  ('hindu', 'brahmin-jangid', 'Brahmin - Jangid'),
  ('hindu', 'brahmin-jhadua', 'Brahmin - Jhadua'),
  ('hindu', 'brahmin-jhijhotiya', 'Brahmin - Jhijhotiya'),
  ('hindu', 'brahmin-kannada-madhva', 'Brahmin - Kannada Madhva'),
  ('hindu', 'brahmin-karhade', 'Brahmin - Karhade'),
  ('hindu', 'brahmin-kashmiri-pandit', 'Brahmin - Kashmiri Pandit'),
  ('hindu', 'brahmin-khandelwal', 'Brahmin - Khandelwal'),
  ('hindu', 'brahmin-koknastha', 'Brahmin - Koknastha'),
  ('hindu', 'brahmin-kota', 'Brahmin - Kota'),
  ('hindu', 'brahmin-kulin', 'Brahmin - Kulin'),
  ('hindu', 'brahmin-kumaoni', 'Brahmin - Kumaoni'),
  ('hindu', 'brahmin-madhwa', 'Brahmin - Madhwa'),
  ('hindu', 'brahmin-maharashtrian', 'Brahmin - Maharashtrian'),
  ('hindu', 'brahmin-maithil', 'Brahmin - Maithil'),
  ('hindu', 'brahmin-modh', 'Brahmin - Modh'),
  ('hindu', 'brahmin-mohyal', 'Brahmin - Mohyal'),
  ('hindu', 'brahmin-nagar', 'Brahmin - Nagar'),
  ('hindu', 'brahmin-namboodiri', 'Brahmin - Namboodiri'),
  ('hindu', 'brahmin-niyogi', 'Brahmin - Niyogi'),
  ('hindu', 'brahmin-paliwal', 'Brahmin - Paliwal'),
  ('hindu', 'brahmin-panda', 'Brahmin - Panda'),
  ('hindu', 'brahmin-pandit', 'Brahmin - Pandit'),
  ('hindu', 'brahmin-pareek', 'Brahmin - Pareek'),
  ('hindu', 'brahmin-pushkarna', 'Brahmin - Pushkarna'),
  ('hindu', 'brahmin-rajgor', 'Brahmin - Rajgor'),
  ('hindu', 'brahmin-rarhi', 'Brahmin - Rarhi'),
  ('hindu', 'brahmin-rigvedi', 'Brahmin - Rigvedi'),
  ('hindu', 'brahmin-rudraj', 'Brahmin - Rudraj'),
  ('hindu', 'brahmin-sakaldwipi', 'Brahmin - Sakaldwipi'),
  ('hindu', 'brahmin-sanadya', 'Brahmin - Sanadya'),
  ('hindu', 'brahmin-sanketi', 'Brahmin - Sanketi'),
  ('hindu', 'brahmin-saraswat', 'Brahmin - Saraswat'),
  ('hindu', 'brahmin-saryuparin', 'Brahmin - Saryuparin'),
  ('hindu', 'brahmin-shaiva', 'Brahmin - Shaiva'),
  ('hindu', 'brahmin-sharma', 'Brahmin - Sharma'),
  ('hindu', 'brahmin-shivalli', 'Brahmin - Shivalli'),
  ('hindu', 'brahmin-shri-gaud', 'Brahmin - Shri Gaud'),
  ('hindu', 'brahmin-shri-mali', 'Brahmin - Shri Mali'),
  ('hindu', 'brahmin-smartha', 'Brahmin - Smartha'),
  ('hindu', 'brahmin-sri-vaishnava', 'Brahmin - Sri Vaishnava'),
  ('hindu', 'brahmin-stanika', 'Brahmin - Stanika'),
  ('hindu', 'brahmin-tyagi', 'Brahmin - Tyagi'),
  ('hindu', 'brahmin-vaidiki', 'Brahmin - Vaidiki'),
  ('hindu', 'brahmin-vaikhawas', 'Brahmin - Vaikhawas'),
  ('hindu', 'brahmin-valam', 'Brahmin - Valam'),
  ('hindu', 'brahmin-velanadu', 'Brahmin - Velanadu'),
  ('hindu', 'brahmin-viswa', 'Brahmin - Viswa'),
  ('hindu', 'brahmin-vyas', 'Brahmin - Vyas'),
  ('hindu', 'bunt-shetty', 'Bunt / Shetty'),
  ('hindu', 'ckp', 'CKP'),
  ('hindu', 'chambhar', 'Chambhar'),
  ('hindu', 'chandravanshi-kahar', 'Chandravanshi Kahar'),
  ('hindu', 'chasa', 'Chasa'),
  ('hindu', 'chattada-sri-vaishnava', 'Chattada Sri Vaishnava'),
  ('hindu', 'chaudary', 'Chaudary'),
  ('hindu', 'chaurasia', 'Chaurasia'),
  ('hindu', 'chennadasar', 'Chennadasar'),
  ('hindu', 'chettiar', 'Chettiar'),
  ('hindu', 'chhetri', 'Chhetri'),
  ('hindu', 'chippolu-mera', 'Chippolu (Mera)'),
  ('hindu', 'coorgi', 'Coorgi'),
  ('hindu', 'devadiga', 'Devadiga'),
  ('hindu', 'devanga', 'Devanga'),
  ('hindu', 'devar-thevar-mukkulathor', 'Devar / Thevar / Mukkulathor'),
  ('hindu', 'devendra-kula-vellalar', 'Devendra Kula Vellalar'),
  ('hindu', 'dhangar', 'Dhangar'),
  ('hindu', 'dheevara', 'Dheevara'),
  ('hindu', 'dhiman', 'Dhiman'),
  ('hindu', 'dhoba', 'Dhoba'),
  ('hindu', 'dhobi', 'Dhobi'),
  ('hindu', 'dusadh', 'Dusadh'),
  ('hindu', 'ediga', 'Ediga'),
  ('hindu', 'ezhava', 'Ezhava'),
  ('hindu', 'ezhuthachan', 'Ezhuthachan'),
  ('hindu', 'gabit', 'Gabit'),
  ('hindu', 'ganda', 'Ganda'),
  ('hindu', 'gandla', 'Gandla'),
  ('hindu', 'ganiga', 'Ganiga'),
  ('hindu', 'garhwali', 'Garhwali'),
  ('hindu', 'gavara', 'Gavara'),
  ('hindu', 'gawali', 'Gawali'),
  ('hindu', 'ghisadi', 'Ghisadi'),
  ('hindu', 'ghumar', 'Ghumar'),
  ('hindu', 'goala', 'Goala'),
  ('hindu', 'goan', 'Goan'),
  ('hindu', 'goswami', 'Goswami'),
  ('hindu', 'goud', 'Goud'),
  ('hindu', 'gounder', 'Gounder'),
  ('hindu', 'gowda', 'Gowda'),
  ('hindu', 'gramani', 'Gramani'),
  ('hindu', 'gudia', 'Gudia'),
  ('hindu', 'gujjar', 'Gujjar'),
  ('hindu', 'gupta', 'Gupta'),
  ('hindu', 'guptan', 'Guptan'),
  ('hindu', 'gurjar', 'Gurjar'),
  ('hindu', 'hegde', 'Hegde'),
  ('hindu', 'helava', 'Helava'),
  ('hindu', 'intercaste', 'Intercaste'),
  ('hindu', 'irani', 'Irani'),
  ('hindu', 'jaalari', 'Jaalari'),
  ('hindu', 'jaiswal', 'Jaiswal'),
  ('hindu', 'jandra', 'Jandra'),
  ('hindu', 'jangam', 'Jangam'),
  ('hindu', 'jangra', 'Jangra'),
  ('hindu', 'jat', 'Jat'),
  ('hindu', 'jatav', 'Jatav'),
  ('hindu', 'jogi-nath', 'Jogi (Nath)'),
  ('hindu', 'kachara', 'Kachara'),
  ('hindu', 'kaibarta', 'Kaibarta'),
  ('hindu', 'kakkalan', 'Kakkalan'),
  ('hindu', 'kalar', 'Kalar'),
  ('hindu', 'kalinga', 'Kalinga'),
  ('hindu', 'kalinga-vysya', 'Kalinga Vysya'),
  ('hindu', 'kalita', 'Kalita'),
  ('hindu', 'kalwar', 'Kalwar'),
  ('hindu', 'kamboj', 'Kamboj'),
  ('hindu', 'kamma', 'Kamma'),
  ('hindu', 'kanak-rajulu', 'Kanak Rajulu'),
  ('hindu', 'kandara', 'Kandara'),
  ('hindu', 'kapu', 'Kapu'),
  ('hindu', 'karana', 'Karana'),
  ('hindu', 'karmakar', 'Karmakar'),
  ('hindu', 'karuneegar', 'Karuneegar'),
  ('hindu', 'karwa', 'Karwa'),
  ('hindu', 'kasar', 'Kasar'),
  ('hindu', 'kashyap', 'Kashyap'),
  ('hindu', 'kayastha', 'Kayastha'),
  ('hindu', 'khatri', 'Khatri'),
  ('hindu', 'koli', 'Koli'),
  ('hindu', 'kongu-vellala-gounder', 'Kongu Vellala Gounder'),
  ('hindu', 'konkani', 'Konkani'),
  ('hindu', 'kori', 'Kori'),
  ('hindu', 'koshti', 'Koshti'),
  ('hindu', 'kshatriya', 'Kshatriya'),
  ('hindu', 'kshatriya-raju', 'Kshatriya Raju'),
  ('hindu', 'kumaoni', 'Kumaoni'),
  ('hindu', 'kumhar', 'Kumhar'),
  ('hindu', 'kummari', 'Kummari'),
  ('hindu', 'kunbi', 'Kunbi'),
  ('hindu', 'kurmi', 'Kurmi'),
  ('hindu', 'kuruba', 'Kuruba'),
  ('hindu', 'kuruhina-shetty', 'Kuruhina Shetty'),
  ('hindu', 'kurumbar', 'Kurumbar'),
  ('hindu', 'kushwaha', 'Kushwaha'),
  ('hindu', 'kutchi', 'Kutchi'),
  ('hindu', 'lambani', 'Lambani'),
  ('hindu', 'leva-patil', 'Leva Patil'),
  ('hindu', 'lingayat', 'Lingayat'),
  ('hindu', 'lodhi-rajput', 'Lodhi Rajput'),
  ('hindu', 'lohana', 'Lohana'),
  ('hindu', 'lohar', 'Lohar'),
  ('hindu', 'lubana', 'Lubana'),
  ('hindu', 'madiga', 'Madiga'),
  ('hindu', 'mahajan', 'Mahajan'),
  ('hindu', 'mahar', 'Mahar'),
  ('hindu', 'mahendra', 'Mahendra'),
  ('hindu', 'maheshwari', 'Maheshwari'),
  ('hindu', 'mahishya', 'Mahishya'),
  ('hindu', 'majabi', 'Majabi'),
  ('hindu', 'mala', 'Mala'),
  ('hindu', 'mali', 'Mali'),
  ('hindu', 'mangalorean', 'Mangalorean'),
  ('hindu', 'manipuri', 'Manipuri'),
  ('hindu', 'mapila', 'Mapila'),
  ('hindu', 'marar', 'Marar'),
  ('hindu', 'maratha', 'Maratha'),
  ('hindu', 'maratha-kshatriya', 'Maratha Kshatriya'),
  ('hindu', 'maruthuvar', 'Maruthuvar'),
  ('hindu', 'matang', 'Matang'),
  ('hindu', 'maurya', 'Maurya'),
  ('hindu', 'meena', 'Meena'),
  ('hindu', 'meenavar', 'Meenavar'),
  ('hindu', 'modak', 'Modak'),
  ('hindu', 'mogaveera', 'Mogaveera'),
  ('hindu', 'mudaliar', 'Mudaliar'),
  ('hindu', 'mudiraj', 'Mudiraj'),
  ('hindu', 'muthuraja', 'Muthuraja'),
  ('hindu', 'naagavamsam', 'Naagavamsam'),
  ('hindu', 'nadar', 'Nadar'),
  ('hindu', 'nagaralu', 'Nagaralu'),
  ('hindu', 'naicker', 'Naicker'),
  ('hindu', 'naidu', 'Naidu'),
  ('hindu', 'nair', 'Nair'),
  ('hindu', 'namasudra-namassey', 'Namasudra / Namassey'),
  ('hindu', 'nambiar', 'Nambiar'),
  ('hindu', 'nayak', 'Nayak'),
  ('hindu', 'nayaka', 'Nayaka'),
  ('hindu', 'neeli', 'Neeli'),
  ('hindu', 'nema', 'Nema'),
  ('hindu', 'nhavi', 'Nhavi'),
  ('hindu', 'obc-barber-naayee', 'OBC - Barber / Naayee'),
  ('hindu', 'oswal', 'Oswal'),
  ('hindu', 'otari', 'Otari'),
  ('hindu', 'padmasali', 'Padmasali'),
  ('hindu', 'pal', 'Pal'),
  ('hindu', 'panchal', 'Panchal'),
  ('hindu', 'panicker', 'Panicker'),
  ('hindu', 'parkava-kulam', 'Parkava Kulam'),
  ('hindu', 'parmar', 'Parmar'),
  ('hindu', 'patel', 'Patel'),
  ('hindu', 'patil', 'Patil'),
  ('hindu', 'paundra', 'Paundra'),
  ('hindu', 'perika', 'Perika'),
  ('hindu', 'pillai', 'Pillai'),
  ('hindu', 'prajapati', 'Prajapati'),
  ('hindu', 'rajaka', 'Rajaka'),
  ('hindu', 'rajbhar', 'Rajbhar'),
  ('hindu', 'rajbonshi', 'Rajbonshi'),
  ('hindu', 'rajput', 'Rajput'),
  ('hindu', 'rajput-garhwali', 'Rajput - Garhwali'),
  ('hindu', 'rajput-kumaoni', 'Rajput - Kumaoni'),
  ('hindu', 'raju', 'Raju'),
  ('hindu', 'rama-kshatriya', 'Rama Kshatriya'),
  ('hindu', 'ramdasia', 'Ramdasia'),
  ('hindu', 'ramgharia', 'Ramgharia'),
  ('hindu', 'rauniyar', 'Rauniyar'),
  ('hindu', 'rawat', 'Rawat'),
  ('hindu', 'reddy', 'Reddy'),
  ('hindu', 'ror', 'Ror'),
  ('hindu', 'sc', 'SC'),
  ('hindu', 'skp', 'SKP'),
  ('hindu', 'st', 'ST'),
  ('hindu', 'sadgope', 'Sadgope'),
  ('hindu', 'saha', 'Saha'),
  ('hindu', 'sahu', 'Sahu'),
  ('hindu', 'saini', 'Saini'),
  ('hindu', 'saliya', 'Saliya'),
  ('hindu', 'sathwara', 'Sathwara'),
  ('hindu', 'satnami', 'Satnami'),
  ('hindu', 'sengar', 'Sengar'),
  ('hindu', 'settibalija', 'Settibalija'),
  ('hindu', 'shah', 'Shah'),
  ('hindu', 'shimpi', 'Shimpi'),
  ('hindu', 'sindhi', 'Sindhi'),
  ('hindu', 'sindhi-amil', 'Sindhi - Amil'),
  ('hindu', 'sindhi-bhaiband', 'Sindhi - Bhaiband'),
  ('hindu', 'sindhi-hyderabadi', 'Sindhi - Hyderabadi'),
  ('hindu', 'sindhi-larai', 'Sindhi - Larai'),
  ('hindu', 'sindhi-sahiti', 'Sindhi - Sahiti'),
  ('hindu', 'sindhi-sakkhar', 'Sindhi - Sakkhar'),
  ('hindu', 'sindhi-sehwani', 'Sindhi - Sehwani'),
  ('hindu', 'sindhi-shikarpuri', 'Sindhi - Shikarpuri'),
  ('hindu', 'sindhi-thatai', 'Sindhi - Thatai'),
  ('hindu', 'somvanshi', 'Somvanshi'),
  ('hindu', 'sonar', 'Sonar'),
  ('hindu', 'soni', 'Soni'),
  ('hindu', 'sourashtra', 'Sourashtra'),
  ('hindu', 'sozhiya-vellalar', 'Sozhiya Vellalar'),
  ('hindu', 'srisayana', 'Srisayana'),
  ('hindu', 'suguna', 'Suguna'),
  ('hindu', 'sutar', 'Sutar'),
  ('hindu', 'swakula-sali', 'Swakula Sali'),
  ('hindu', 'tamboli', 'Tamboli'),
  ('hindu', 'tammali', 'Tammali'),
  ('hindu', 'tanti', 'Tanti'),
  ('hindu', 'teli', 'Teli'),
  ('hindu', 'thakkar', 'Thakkar'),
  ('hindu', 'thakur', 'Thakur'),
  ('hindu', 'thigala', 'Thigala'),
  ('hindu', 'thiyya', 'Thiyya'),
  ('hindu', 'tili', 'Tili'),
  ('hindu', 'togata', 'Togata'),
  ('hindu', 'tonk-kshatriya', 'Tonk Kshatriya'),
  ('hindu', 'turupu-kapu', 'Turupu Kapu'),
  ('hindu', 'urali-gounder', 'Urali Gounder'),
  ('hindu', 'vada-balija', 'Vada Balija'),
  ('hindu', 'vaddera', 'Vaddera'),
  ('hindu', 'vaish', 'Vaish'),
  ('hindu', 'vaishnava', 'Vaishnava'),
  ('hindu', 'vaishya', 'Vaishya'),
  ('hindu', 'vaishya-vani', 'Vaishya Vani'),
  ('hindu', 'vani', 'Vani'),
  ('hindu', 'vanjari', 'Vanjari'),
  ('hindu', 'vankar', 'Vankar'),
  ('hindu', 'vannar', 'Vannar'),
  ('hindu', 'vannia-kula-kshatriya', 'Vannia Kula Kshatriya'),
  ('hindu', 'variar', 'Variar'),
  ('hindu', 'varshney', 'Varshney'),
  ('hindu', 'veera-saivam', 'Veera Saivam'),
  ('hindu', 'velaan', 'Velaan'),
  ('hindu', 'velama', 'Velama'),
  ('hindu', 'vellalar', 'Vellalar'),
  ('hindu', 'veluthedathu-nair', 'Veluthedathu Nair'),
  ('hindu', 'vettuva-gounder', 'Vettuva Gounder'),
  ('hindu', 'vishwakarma', 'Vishwakarma'),
  ('hindu', 'viswabrahmin', 'Viswabrahmin'),
  ('hindu', 'vokkaliga', 'Vokkaliga'),
  ('hindu', 'vysya', 'Vysya'),
  ('hindu', 'yadav', 'Yadav'),
  ('hindu', 'yellapu', 'Yellapu'),
  ('hindu', 'other', 'Other'),
  ('muslim', 'ansari', 'Ansari'),
  ('muslim', 'arain', 'Arain'),
  ('muslim', 'awan', 'Awan'),
  ('muslim', 'bohra', 'Bohra'),
  ('muslim', 'dekkani', 'Dekkani'),
  ('muslim', 'dudekula', 'Dudekula'),
  ('muslim', 'hanafi', 'Hanafi'),
  ('muslim', 'jat', 'Jat'),
  ('muslim', 'khoja', 'Khoja'),
  ('muslim', 'lebbai', 'Lebbai'),
  ('muslim', 'malik', 'Malik'),
  ('muslim', 'mapila', 'Mapila'),
  ('muslim', 'maraicar', 'Maraicar'),
  ('muslim', 'memon', 'Memon'),
  ('muslim', 'mughal', 'Mughal'),
  ('muslim', 'pathan', 'Pathan'),
  ('muslim', 'qureshi', 'Qureshi'),
  ('muslim', 'rajput', 'Rajput'),
  ('muslim', 'rowther', 'Rowther'),
  ('muslim', 'shafi', 'Shafi'),
  ('muslim', 'sheikh', 'Sheikh'),
  ('muslim', 'shia', 'Shia'),
  ('muslim', 'shia-imami-ismaili', 'Shia Imami Ismaili'),
  ('muslim', 'shia-ithna-ashariyyah', 'Shia Ithna Ashariyyah'),
  ('muslim', 'shia-zaidi', 'Shia Zaidi'),
  ('muslim', 'siddiqui', 'Siddiqui'),
  ('muslim', 'sunni', 'Sunni'),
  ('muslim', 'syed', 'Syed'),
  ('muslim', 'other', 'Other'),
  ('christian', 'anglo-indian', 'Anglo Indian'),
  ('christian', 'born-again', 'Born Again'),
  ('christian', 'brethren', 'Brethren'),
  ('christian', 'cms', 'CMS'),
  ('christian', 'church-of-north-india', 'Church of North India'),
  ('christian', 'church-of-south-india', 'Church of South India'),
  ('christian', 'evangelist', 'Evangelist'),
  ('christian', 'jacobite', 'Jacobite'),
  ('christian', 'knanaya', 'Knanaya'),
  ('christian', 'knanaya-catholic', 'Knanaya Catholic'),
  ('christian', 'knanaya-jacobite', 'Knanaya Jacobite'),
  ('christian', 'latin-catholic', 'Latin Catholic'),
  ('christian', 'malankara', 'Malankara'),
  ('christian', 'marthoma', 'Marthoma'),
  ('christian', 'methodist', 'Methodist'),
  ('christian', 'orthodox', 'Orthodox'),
  ('christian', 'pentecost', 'Pentecost'),
  ('christian', 'presbyterian', 'Presbyterian'),
  ('christian', 'protestant', 'Protestant'),
  ('christian', 'roman-catholic', 'Roman Catholic'),
  ('christian', 'seventh-day-adventist', 'Seventh-day Adventist'),
  ('christian', 'syrian-catholic', 'Syrian Catholic'),
  ('christian', 'syrian-jacobite', 'Syrian Jacobite'),
  ('christian', 'syrian-orthodox', 'Syrian Orthodox'),
  ('christian', 'syro-malabar', 'Syro Malabar'),
  ('christian', 'syro-malankara', 'Syro Malankara'),
  ('christian', 'other', 'Other'),
  ('sikh', 'ahluwalia', 'Ahluwalia'),
  ('sikh', 'arora', 'Arora'),
  ('sikh', 'bhatia', 'Bhatia'),
  ('sikh', 'gursikh', 'Gursikh'),
  ('sikh', 'jat', 'Jat'),
  ('sikh', 'kamboj', 'Kamboj'),
  ('sikh', 'khatri', 'Khatri'),
  ('sikh', 'labana', 'Labana'),
  ('sikh', 'lubana', 'Lubana'),
  ('sikh', 'majabi', 'Majabi'),
  ('sikh', 'ramdasia', 'Ramdasia'),
  ('sikh', 'ramgharia', 'Ramgharia'),
  ('sikh', 'rajput', 'Rajput'),
  ('sikh', 'saini', 'Saini'),
  ('sikh', 'other', 'Other'),
  ('jain', 'agarwal', 'Agarwal'),
  ('jain', 'digambar', 'Digambar'),
  ('jain', 'khandelwal', 'Khandelwal'),
  ('jain', 'kutchi', 'Kutchi'),
  ('jain', 'oswal', 'Oswal'),
  ('jain', 'porwal', 'Porwal'),
  ('jain', 'saitwal', 'Saitwal'),
  ('jain', 'shwetamber', 'Shwetamber'),
  ('jain', 'sthanakvasi', 'Sthanakvasi'),
  ('jain', 'terapanthi', 'Terapanthi'),
  ('jain', 'other', 'Other'),
  ('buddhist', 'mahayana', 'Mahayana'),
  ('buddhist', 'navayana', 'Navayana'),
  ('buddhist', 'newar', 'Newar'),
  ('buddhist', 'theravada', 'Theravada'),
  ('buddhist', 'tibetan', 'Tibetan'),
  ('buddhist', 'vajrayana', 'Vajrayana'),
  ('buddhist', 'other', 'Other'),
  ('parsi', 'irani', 'Irani'),
  ('parsi', 'parsi', 'Parsi'),
  ('parsi', 'other', 'Other'),
  ('jewish', 'baghdadi', 'Baghdadi'),
  ('jewish', 'bene-israel', 'Bene Israel'),
  ('jewish', 'cochin', 'Cochin'),
  ('jewish', 'other', 'Other'),
  ('spiritual', 'spiritual-not-religious', 'Spiritual - not religious'),
  ('spiritual', 'other', 'Other'),
  ('other', 'other', 'Other')
) as v(religion_slug, slug, name) on r.slug = v.religion_slug
on conflict (religion_id, slug) do nothing;

commit;
